//create product constants
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

//get all products 
export const LIST_OF_PRODUCTS_REQUEST = "LIST_OF_PRODUCTS_REQUEST";
export const LIST_OF_PRODUCTS_SUCCESS = "LIST_OF_PRODUCTS_SUCCESS";
export const LIST_OF_PRODUCTS_FAIL = "LIST_OF_PRODUCTS_FAIL";


//constants to get details of product
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

//const to get user products
export const USER_PRODUCTS_REQUEST = "USER_PRODUCTS_REQUEST";
export const USER_PRODUCTS_SUCCESS = "USER_PRODUCTS_SUCCESS";
export const USER_PRODUCTS_FAIL = "USER_PRODUCTS_FAIL";

