//declare three constants here
export const LIST_OF_PRODUCTS_REQUEST = "LIST_OF_PRODUCTS_REQUEST";
export const LIST_OF_PRODUCTS_SUCCESS = "LIST_OF_PRODUCTS_SUCCESS";
export const LIST_OF_PRODUCTS_FAIL = "LIST_OF_PRODUCTS_FAIL";


//constants to get details of product
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
