//create product constants
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

//get all products 
export const LIST_OF_PRODUCTS_REQUEST = "LIST_OF_PRODUCTS_REQUEST";
export const LIST_OF_PRODUCTS_SUCCESS = "LIST_OF_PRODUCTS_SUCCESS";
export const LIST_OF_PRODUCTS_FAIL = "LIST_OF_PRODUCTS_FAIL";


//constants to get details of product
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

//constants to get user products
export const USER_PRODUCTS_REQUEST = "USER_PRODUCTS_REQUEST";
export const USER_PRODUCTS_SUCCESS = "USER_PRODUCTS_SUCCESS";
export const USER_PRODUCTS_FAIL = "USER_PRODUCTS_FAIL";

//constants to find a product for update
export const GET_PRODUCT_FOR_UPDATE_REQUEST="GET_PRODUCT_FOR_UPDATE_REQUEST";
export const GET_PRODUCT_FOR_UPDATE_SUCCESS="GET_PRODUCT_FOR_UPDATE_SUCCESS";
export const GET_PRODUCT_FOR_UPDATE_FAIL="GET_PRODUCT_FOR_UPDATE_FAIL";
export const GET_PRODUCT_FOR_UPDATE_RESET = "GET_PRODUCT_FOR_UPDATE_RESET";

//constants to update a user product
export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";

