//create a store constants
export const CREATE_STORE_REQUEST = "CREATE_STORE_REQUEST";
export const CREATE_STORE_SUCCESS = "CREATE_STORE_SUCCESS";
export const CREATE_STORE_FAIL = "CREATE_STORE_FAIL";

//get store actions
export const GET_STORES_REQUEST = "GET_STORES_REQUEST";
export const GET_STORES_SUCCESS = "GET_STORES_SUCCESS";
export const GET_STORES_FAIL = "GET_STORES_FAIL";

//get single store constants, get store details
export const GET_SINGLE_STORE_REQUEST = "GET_SINGLE_STORE_REQUEST";
export const GET_SINGLE_STORE_SUCCESS = "GET_SINGLE_STORE_SUCCESS";
export const GET_SINGLE_STORE_FAIL = "GET_SINGLE_STORE_FAIL";

//get user store
export const GET_USERSTORE_REQUEST = "GET_USERSTORE_REQUEST";
export const GET_USERSTORE_SUCCESS = "GET_USERSTORE_SUCCESS";
export const GET_USERSTORE_FAIL = "GET_USERSTORE_FAIL";