//constants to create widthdraw 
export const CREATE_WIDTHDRAW_REQUEST="CREATE_WIDTHDRAW_REQUEST"
export const CREATE_WIDTHDRAW_SUCCESS="CREATE_WIDTHDRAW_SUCCESS"
export const CREATE_WIDTHDRAW_FAIL="CREATE_WIDTHDRAW_FAIL"
export const CREATE_WIDTHDRAW_RESET="CREATE_WIDTHDRAW_RESET"

//get widthdrawals
export const GET_WIDTHDRAWAL_REQUEST="GET_WIDTHDRAWAL_REQUEST"
export const GET_WIDTHDRAWAL_SUCCESS="GET_WIDTHDRAWAL_SUCCESS"
export const GET_WIDTHDRAWAL_FAIL="GET_WIDTHDRAWAL_FAIL"